### ISSUE TITLE
Implement a BaseFactory class

### ISSUE THREAD

**Issue by chx2** [tipoff/support#129]
In https://github.com/tipoff/locations/pull/110, it was rather helpful to create a factory state to better improve the data that a given factory could generate in addition to making it easier to browser test the creation of resources.

- [Our implementation of a factory state](https://github.com/tipoff/locations/blob/main/database/factories/GmbHourFactory.php#L43)
- [Factory State Documentation](https://laravel.com/docs/8.x/database-testing#factory-states)

Referring to how tipoff packages tend to have simliar fields such as `creator_id` and `updater_id` for example, it may be beneficial to have a BaseFactory class that would extend `Illuminate\Database\Eloquent\Factories\Factory`. Once extended into a package model factory, `definition` could be called as normal but factories would then be able to have access to states visible in the BaseFactory that could be chained for use wherever needed.

**Comment by drewroberts** [comment]
@pdbreen What are your thoughts on this? Should @chx2 go ahead and create a draft PR for what he has in mind?

**Comment by pdbreen** [comment]
doesn't seem worth it to me - not sure what (meaningful) states would be common across different models

edit:  here's an example of a factory with a bunch of states -- https://github.com/tipoff/vouchers/blob/main/database/factories/VoucherFactory.php -- but none of these are relevant to any other model.

**Comment by chx2** [comment]
That makes sense. For now I will keep use of factory states per package basis.

**Comment by drewroberts** [comment]
Thank you both. @chx2 Keep creating issues like this and posting ideas to improve the project.
